# Generated by Django 4.2.2 on 2024-06-19 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Туристичке             <a href="https://turizamrs.org/destinacije/">дестинације</a> Републике Српске', max_length=20, unique=True)),
                ('po_box', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше име или надимак, по жељи! :-)', max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('region', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=30, null=True)),
                ('drink', models.CharField(max_length=30, null=True)),
                ('entertainment', models.CharField(max_length=30, null=True)),
                ('recreation', models.CharField(max_length=30, null=True)),
                ('sport', models.CharField(max_length=30, null=True)),
                ('hobby', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField(default='Још увијек нема коментара', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tourism.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='location_name_case_insensitive_unique', violation_error_message='Локација већ постоји (велика/мала слова нису битна!)'),
        ),
    ]
