# Generated by Django 4.2.2 on 2024-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Туристичке <a href="https://turizamrs.org/destinacije/">дестинације</a> Републике Српске', max_length=20, unique=True),
        ),
    ]
